### ISSUE TITLE
Error downloading BHSA

### ISSUE THREAD

**Issue by peterbekins** [ETCBC/bhsa#4]
Hello, I am interested in using text-fabric for my research. I have downloaded the package, but I am having trouble downloading the BHSA data. After running "text-fabric bhsa" I get the following errors: 

getConfig: Parent module 'tf.extra.bhsa-app' not loaded, cannot perform relative import
getConfig: Data source "bhsa" not found

**Comment by MartijnNaaijer** [comment]
Hi Peter, I am not sure how and what exactly you have installed, but the easiest way to go is to install Anaconda first, then install text fabric with "pip install text-fabric" (pip3 on Mac) (see also https://annotation.github.io/text-fabric/about/install.html#install),  then open Jupyter Notebook, which comes with Anaconda. Then run the incantation, which you find on this page (https://nbviewer.jupyter.org/github/annotation/tutorials/blob/master/bhsa/start.ipynb), this loads text fabric and downloads the bhsa-data. 

Let me know if this does not work (martijn.naayer@upcmail.nl).

**Comment by dirkroorda** [comment]
Hi Peter,
the error you mention must be produced by an older version of text-fabric, 6 or earlier. We are now at 8.4.0.
I'm not sure how you ended up with a version this old.
Let us know if you encounter further problems.

**Comment by peterbekins** [comment]
Hi Dirk, yes that sounds like the issue! I simply used "pip install text-fabric" and I have Python 3.6 installed in miniconda. It looks like it installed text-fabric 5.4.1. 

Is there a way to force it to install the latest version or is there an issue with using miniconda and/or Python 3.6?

**Comment by dirkroorda** [comment]
Hi Peter,

I have never encountered the issue that pip installed an older version without being instructed to do so.
It could be this: text-fabric requires at least Python 3.6.3.
But I put that requirement in somewhere during version 5, first as python 3.6, and later more precisely as 3.6.3.

So I guess you had a Python version between 3.6.0 and 3.6.2.x, and pip asked for the newest Text-Fabric version that for which your Python installation satisfied the requirements.

By the way, do you have a compelling reason to stick to Python 3.6? I'm asking because I'm getting tempted to use features of Python 3.8 in Text-Fabric (async library, walrus operator, etc).

**Comment by peterbekins** [comment]
Python 3.6 is simply what installed with miniconda several years ago when I began learning Python. I guess "conda upgrade conda" gets you to the latest release of the version you started with, so that's why I went to 3.6.10. This is the first time I have run into an issue with it, but I could certainly upgrade to 3.8 if needed.
