### ISSUE TITLE
Most slots missing in tf/2017/gloss.tf

### ISSUE THREAD

**Issue by rubiot** [ETCBC/bhsa#6]
I noticed the 2017 version of gloss.tf seems to be missing most glosses. Is there a reason for this?
```
~/github/etcbc/bhsa$ wc -l tf/4b/gloss.tf tf/2017/gloss.tf 
 435818 tf/4b/gloss.tf
   9245 tf/2017/gloss.tf
```

**Comment by dirkroorda** [comment]
Hi Rúbio,

yes, at some point we decided that is was redundant to have the glosses on all word nodes, since they are a lexeme property. So in 2017 only lexeme nodes carry the gloss feature.

Then we discovered that in some situations it is very convenient to have the gloss nodes on all occurrences, so in version `c` we added them back. I hope there will be a brand new data version `2021` soon, and then we will put them back also there.

In the meanwhile, could you explain how the lack of `gloss` on word nodes is problematic for you? Maybe I can help with a workaround!

**Comment by rubiot** [comment]
Thank you for the prompt answer! The problem is that the `gloss.tf` file for version 2017 only has 9245 lines, while the old 4b version has 435818. I guess this may be unintentional.

On a side note it's great to know there's a new version coming soon. Thank you for all the hard work!

**Comment by rubiot** [comment]
I see `oslot.tf` does the linking between words and lexemes, but it is possible to do that out of the big table?

**Comment by dirkroorda** [comment]
It should, but it was very unthoughtful of me to not to include the column that you need for this, namely a column that gives the lexeme node for every word.

However, it turned out extremely easy to add that column, which I did.

You can recreate the table by means of this notebook: https://nbviewer.jupyter.org/github/ETCBC/bhsa/blob/master/programs/bigTables.ipynb

And then (for Pandas), this one https://nbviewer.jupyter.org/github/ETCBC/bhsa/blob/master/programs/bigTablesP.ipynb
and for R this one https://nbviewer.jupyter.org/github/ETCBC/bhsa/blob/master/programs/bigTablesR.ipynb
(if you need them).

Make sure you have the latest version (`git pull https://github.com/ETCBC/bhsa`) and the latest version of Text-Fabric (`pip3 install text-fabric`).

I just generated the big table without issue.

Just curious, do you work in Pandas or R or with other ways to deal with the big table?

**Comment by rubiot** [comment]
Thank you, this solves my problem beautifully.

> Just curious, do you work in Pandas or R or with other ways to deal with the big table?

I'm running the big table through a Perl script, but that's because I'm more comfortable with Perl.
